### ISSUE TITLE
Should be able to "test" a backend is configured correctly

### ISSUE THREAD

**Issue by borischen** [splunk/splunk-shuttl#106]
Use case:

User is configuring Shuttl to write to a backend. Wants to know that configured correctly, without actually shuttling a bucket.

Functionality:
Based on a config, be able to, via rest/cli, write a zero byte test file to see it written to the backend. And alternatively, if fails, then write the failure to the log file Clean-up any test files upon startup of Shuttl

**Comment by petterik** [comment]
Since we don't want to be dependent on what backend the users of Shuttl uses for this script, and we don't have any remove-bucket endpoint, there's no real way of tearing down this test.

The test does remind the user to remove the archived buckets, every time they run the script.

**Comment by petterik** [comment]
The script for testing if a configured Shuttl is working lives in a built and installed shuttl app at:
$SPLUNK_HOME/etc/apps/shuttl/bin/testArchivingBucket.sh
