### ISSUE TITLE
Support multiple parallel thaw requests

### ISSUE THREAD

**Issue by petterik** [splunk/splunk-shuttl#25]
Buckets that are already thawed should not be thawed again.

Todo:
- Check if a bucket is already thawed before thawing the bucket.

**Comment by borischen** [comment]
this isn't parallel requests, this is a duplicate request, no? 

If there are requests in parallel, do we have some sort of lock to prevent multiple duplicate thaw requests happening concurrently?

**Comment by petterik** [comment]
That's true. There's nothing checking if a bucket is already being thawed or is already thawed. Implementing this will make parallel and duplicate thaw requests.

The locking code we use for archiving can be totally reused and there's not much other code needed. If I can't get it done this week because of thesis work, I can get it done this weekend.

**Comment by petterik** [comment]
New algorithm for parallel thawing:

```
def for_all_buckets_to_thaw: 
  if lock_for_bucket_to_thaw_is_acquired:
    Transfer_bucket_to_temporary_location
    Move_thawed_bucket_to_thaw_location
    Release_thaw_lock.
  else:
    continue_to_next_bucket_since_it_is_already_being_thawed
```

Errors:
Transfer is interrupted:
1. Code releases thaw lock
2. Will send a notice to the client that thaw failed for that bucket.
3. Continues to thaw next bucket.
4. The interrupted bucket will still lye on the local disk, taking space.

JVM crashes or power failure:
1. Thaw lock is released because of JVM crash (there's a test for this).
2. HTTP status code will hopefully be sent either way. Test this.
3. The next thaw request will be able to thaw the bucket.

Notice:
Bucket that failed to thaw will still take space on the local disk. It should be removed by the next thaw request. But what if there's no other thaw request on that bucket? Create a garbage cleaner that's run every x minute?

Garbage bucket cleaner:

```
def for_every_bucket_in_the_thaw_directory:
  if lock_for_bucket_is_acquired:
    delete_bucket
  else:
    someone_is_apparently_thawing_the_bucket_so_do_nothing
```

**Comment by borischen** [comment]
question: what form does this lock take? if it's a 0 byte file on disk (one per bucket), then upon restart, we can assume all locks were in-transit operations, clean and restart them. 

for thaw requests that fail, not due to a system crash, then having a background thread do cleanup is good. Presumably the state is that a lock is taken, but there is no pending request to fulfill it, or there's no lock, but the bucket is only partially transferred. Either case, it could do a clean up.

**Comment by petterik** [comment]
The locks are a 0 byte file on disk atm and yes, all the locks that exists were in-transit operation. We can clean them upon startup of shuttl, which is better than a garbage bucket cleaner. Thanks!

In either failure case, we should clean them. But as you said, we can restart them as well. It might not be what a user expects to happen, but if we present the information (that we restarted the thaw request) in the UI, it would be great. They should also be able to cancel a thaw request. 
I would be happier as a user if everything continued and I could easily cancel it, instead of having to do the request again.

Hopefully we can even resume the transfers instead of cleaning and restarting. I'll look in to it when as I'm implementing.

**Comment by borischen** [comment]
for now keep it simple. sufficient to clean out failed transfers. auto-resume can be a new feature. for now, user can just re-initiate a transfer

**Comment by petterik** [comment]
Here's a summary of what I did:
1. Thawing thawed bucket -> Does not thaw, because when bucket is already in thawed location (back in Splunk).
2. Thawing is parallel if thawing is done by acquiring a thaw lock before the thaw transfer.
3. Transfer should be done by first transferring to a temporary location, then moving to thaw location. (Atomic transfer)
4. On start up: Remove all temporary transfers and all thaw locks.
