### ISSUE TITLE
Delete/"flush" all thawed buckets

### ISSUE THREAD

**Issue by petterik** [splunk/splunk-shuttl#32]
All the buckets that are successfully thawed should be able to be deleted from the UI.

Do we care about the case where there are multiple users thawing to the same machine, and one user removes both users buckets?

**Comment by borischen** [comment]
I think we need this before conf

To answer question:
1) for multiple users, I'd suggest holding a lock during flush, and if a flush happened, then deny the second flush, and reload the listing
2) then the person can flush based on the revised list
3) we should log the flush operations if we don't already

**Comment by petterik** [comment]
Restrict flushing only to indexes that are being shuttl'd.

**Comment by petterik** [comment]
This is done for now. Create new issues for enhancements and or changes.
