### ISSUE TITLE
instructions on setting up shuttl

### ISSUE THREAD

**Issue by borischen** [splunk/splunk-shuttl#37]
please

**Comment by borischen** [comment]
Assume the following:
- Splunk is installed
- There is a Hadoop instance

From there, we need to tell customers
- basic app install (untar in etc/apps)
- shuttl config file edits needed (name node info, dir locations, etc.)
- splunk config edits (main parameters to control bucket rolling behavior, and calling of archive action)
- include how to config for warm->cold rolls or cold->frozen
- include info on how to config for csv vs splunk bucket formats when archiving
- specification of tmp dir (for file moves)

**Comment by petterik** [comment]
Commit 8508062682bf65edd6a88f4e7d3f2871e4701834 adress everything but "include how to config for warm->cold rolls or cold->frozen"

**Comment by petterik** [comment]
Documentation can be seen in the README.md: https://github.com/splunk/splunk-shuttl/tree/develop#installing-the-app
@andreeriksson

**Comment by borischen** [comment]
warm->cold support is a new feature
