### ISSUE TITLE
Parallel deployment, thawing and listing

### ISSUE THREAD

**Issue by petterik** [splunk/splunk-shuttl#38]
Given n indexers and m search heads, each search head to be able to view and control the indexers.
Each indexer has shuttl setup already.

How would this work?
Comment on this issue with thoughts, discoveries, algorithms and anything else found during research of this issue.

**Comment by petterik** [comment]
This endpoint lists the indexers for distributed search:
/services/search/distributed/peers

**Comment by petterik** [comment]
One could parse the indexers from that endpoint, and for each indexer, call shuttl rest endpoint. Concat responses and view in some UI.
Is this the recommended way of getting indexer IPs? Is there a smoother way?

When we have the IPs to each indexer, we can get the shuttl rest endpoints by calling a "shuttl-port" end point at the indexer. When we have the IP and the shuttl-port, we can call the rest endpoint we want to thaw or list.

I first thought that custom searches would be a good way of communicating between search heads and indexers, and this may be the case for thawing, but we don't want the listing results back as search results. Custom search for thawing could be nice, if we don't care for detailed thawing results, and only return OK. If that's possible. My knowledge and understanding of custom searches is very very slim.

**Comment by petterik** [comment]
@borischen can you ask people at Splunk corp. if there's another way of getting all the search head's indexers?

We can easily test each indexer, to see if they have shuttl installed or not. So getting all of the indexers is fine. I'm mostly wondering if looking at the indexers set up for distributed search is the way to go.
Maybe there's some other way that is more future proof or what not.

Thanks.

**Comment by borischen** [comment]
http://docs.splunk.com/Documentation/Splunk/latest/RESTAPI/RESTdeploy#search.2Fdistributed.2Fpeers

**Comment by petterik** [comment]
What I'm thinking right now:

When either the listing or thawing endpoint is called, shuttl will act accordingly:
1. Execute the request on the node which it is installed on, as is today.
2. Execute the request for each node that is set up as a distributed search peer*.
3. Concatenate results and return to the caller of the rest endpoint.
This way, it doesn't matter for shuttl if it's installed on a search head or on an indexer. We don't need to create our own configuration for the clustering. It's all done by Splunk, which makes our life easier.

*All the request made to the search peers can be run in parallel. Some testing/checking will have to be done to all the search peers to get the shuttl-port on the peer, if shuttl is even installed at all that is.

Seems easy enough?

**Comment by borischen** [comment]
is it all or nothing? (for step 3)

**Comment by petterik** [comment]
Here's a sequence diagram of how we should do the Shuttl-to-Splunk-to-Shuttl's communication:

http://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgU2h1dHRsIHJlcXVlc3RzCgpVSS0-U1BMOiBSAA0GIChpLmUuIHRoYXcpClNQTC0-U0hVABUJClNIVQAhD1VVSUQAIwZVSQAGEAAkCVBlZXJzAEQLTGlzdCBvZiBwABIGSFUtPiJTUEwACgYiOgCBHwhwb3J0PwoADwsAgQgGPHBvcnQ-IG9yIE5PADUISFUANAlzdGFydACBWwggd2l0aACBHwYAgWIJR2l2ZSBtZSB0aGUgcHJvZ3Jlc3Mgb2YAgUALAIFtB3N1bHRzADgKPwBaEwAdCGZvcgAdBwCBAQsAgjYHezpkb25lIDxib29sZWFuPiwgOnIAVwUgPHJlcz59AIJLC01lcmdlZCAAGQZzIGZyb20gAIFTCQCBRgYkZG9uZQCCZgwAgSAGYW5kIGNoYW5nZSBzdGF0ZSBkZXBlbmRpbmcgb24ALgcKbm90ZSBvdmVyIFVJOiBDYW5jZWxpbmcAg0AFIHdvdWxkIGJlIHNpbWlsYXIgdG8AghUKAIQrBw&s=modern-blue

**Comment by petterik** [comment]
The REST calls are relayed to a Shuttl's Splunk's search peers, then the JSON's gets joined/merged. Closing.

**Comment by petterik** [comment]
Regarding using a SearchPeer's <serverName> as host:ip pair. It seems to be true according to docs:
"Note: serverName is not used when adding search peers to a search head. In that case, you identify the search peers through their domain names or IP addresses." (http://docs.splunk.com/Documentation/Splunk/latest/Deploy/Configuredistributedsearch#Manage_distributed_server_names)
