### ISSUE TITLE
splunk app landing page should be a dashboard

### ISSUE THREAD

**Issue by borischen** [splunk/splunk-shuttl#42]
we should have a dashboard of activity/config including
- shuttl config values
- splunk archive configs (i.e. what indexes are being shuttled and associated values)
- archives on hdfs
- hadoop cluster url
- splunk bucket info (buckets in splunk, in hdfs, in transit)
- how many buckets move in last week, last day, last hour
- average size per bucket

**Comment by antonjn** [comment]
If you have not done it yet, run:

``` sh
ant build
```

To tryout the views, run:

``` sh
ant archiver-clean-setup-and-generate-test-buckets
```

Generate test buckets:

``` sh
ant archiver-generate-test-buckets
```

**Comment by petterik** [comment]
Great work, Anton! It just works :)

**Comment by petterik** [comment]
Merging and closing what's in GH-42. 
@antonjn: if you want to add more stuff, create a new issue with what you're adding.
