### ISSUE TITLE
old data being indexed may be causing error

### ISSUE THREAD

**Issue by borischen** [splunk/splunk-shuttl#45]
I try indexing very old data (3+ years), and I'm getting this

06-29-2012 18:09:50.441 -0700 ERROR BucketMover - coldToFrozenScript cmd="/home/boris/hadoopish2/splunk/etc/apps/shuttl/bin/archiveBucket.sh" /home/boris/hadoopish2/splunk/var/lib/splunk/mytest/db/db_1341002607_1341001216_0 exited with non-zero status: exited with code 253

06-29-2012 18:10:15.341 -0700 INFO  BucketMover - will attempt to freeze: /home/boris/hadoopish2/splunk/var/lib/splunk/mytest/colddb/db_1231756732_1231675342_1 because frozenTimePeriodInSecs=120 exceeds difference between now=1341018615 and latest=1231756732

06-29-2012 18:10:15.341 -0700 INFO  BucketMover - will attempt to freeze: /home/boris/hadoopish2/splunk/var/lib/splunk/mytest/colddb/db_1231784662_1231756034_2 because frozenTimePeriodInSecs=120 exceeds difference between now=1341018615 and latest=1231784662

06-29-2012 18:10:15.341 -0700 INFO  BucketMover - will attempt to freeze: /home/boris/hadoopish2/splunk/var/lib/splunk/mytest/colddb/db_1231846282_1231784091_3 because frozenTimePeriodInSecs=120 exceeds difference between now=1341018615 and latest=1231846282

06-29-2012 18:10:15.341 -0700 INFO  BucketMover - will attempt to freeze: /home/boris/hadoopish2/splunk/var/lib/splunk/mytest/colddb/db_1231874338_1231846282_4 because frozenTimePeriodInSecs=120 exceeds difference between now=1341018615 and latest=1231874338

**Comment by petterik** [comment]
@borischen can you do what you did to cause the error, again?
This time, the exit status will make sense, and we can understand if it's either of these errors:

```
public static final int EXIT_INCORRECT_ARGUMENTS = 11;
public static final int EXIT_FILE_NOT_A_DIRECTORY = 12;
public static final int EXIT_FILE_NOT_FOUND = 13;
```

If it's hard to re-produce, I'll get my maths straight and figure out how to get 253 from either -1, -2 or -3 in an 8bit unsigned int.
