### ISSUE TITLE
rename app from shep to shuttl

### ISSUE THREAD

**Issue by borischen** [splunk/splunk-shuttl#5]

**Comment by petterik** [comment]
@andreeriksson @antonjn : Can you check so that the UI survived the renaming from shep to shuttl, and then close this issue?

Thanks

**Comment by antonjn** [comment]
it survived, some other code "broke" it though (BucketRestorer; implemented to always throwing an exception causing a thawed bucket to be seen as not thawn in the UI), did a quick fix for that.

**Comment by borischen** [comment]
Awesome! Thanks!

On Mon, May 21, 2012 at 6:02 PM, Anton <
reply@reply.github.com

**Comment by petterik** [comment]
Great and doh!
I'll make sure something like that can't happen again!

Closing issue
