### ISSUE TITLE
icons for splunk app

### ISSUE THREAD

**Issue by borischen** [splunk/splunk-shuttl#55]
- make sure when listing app, shuttl icon shows up
- shuttl app should have logo in the top left

**Comment by antonjn** [comment]
what does "when listing app" mean? @borischen

**Comment by borischen** [comment]
http://localhost:8000/en-US/app/launcher/home , click on the home tab. The icon shown is a square, so for that, I think we can just take the airplane portion, without the text

Read
http://docs.splunk.com/Documentation/Splunk/latest/Developer/PackageApp
and
http://docs.splunk.com/Documentation/Splunk/latest/Developer/ShareYourWork
