### ISSUE TITLE
remove s2s code

### ISSUE THREAD

**Issue by borischen** [splunk/splunk-shuttl#6]

**Comment by petterik** [comment]
The CLI code is dependent on the s2s sink code.
Ok to remove the CLI code as well?

**Comment by borischen** [comment]
We can delete it if that's all the CLI is used for. Maybe in the future, it'd be good to have a CLI for all the REST endpoints for the archiver, so someone could script what is done via the UI

**Comment by petterik** [comment]
A simple CLI as a UI would be nice indeed. I'll add it as an issue and we can prioritize it later.
