### ISSUE TITLE
thaw screen has invalid dates for buckets

### ISSUE THREAD

**Issue by borischen** [splunk/splunk-shuttl#61]
Example

b_1333377842_1333333189_38  mytestdb    SPLUNK_BUCKET   1970-01-16  1970-01-16  151 MB  hdfs://localhost:9000/archiver_root/archive_data/mycluster/hiro/mytestdb/db_1333377842_1333333189_38/SPLUNK_BUCKET
db_1333502069_1333354200_40     mytestdb    SPLUNK_BUCKET   1970-01-16  1970-01-16  168 MB  hdfs://localhost:9000/archiver_root/archive_data/mycluster/hiro/mytestdb/db_1333502069_1333354200_40/SPLUNK_BUCKET
db_1333510990_1333422240_31     mytestdb    SPLUNK_BUCKET   1970-01-16  1970-01-16  131 MB  hdfs://localhost:9000/archiver_root/archive_data/mycluster/hiro/mytestdb/db_1333510990_1333422240_31/SPLUNK_BUCKET
db_1333534216_1333476761_42     mytestdb    SPLUNK_BUCKET   1970-01-16  1970-01-16  147 MB  hdfs://localhost:9000/archiver_root/archive_data/mycluster/hiro/mytestdb/db_1333534216_1333476761_42/SPLUNK_BUCKET
db_1333548497_1333508923_44     mytestdb    SPLUNK_BUCKET   1970-01-16  1970-01-16  112 MB  hdfs://localhost:9000/archiver_root/archive_data/mycluster/hiro/mytestdb/db_1333548497_1333508923_44/SPLUNK_BUCKET
db_1333563572_1333523435_46     mytestdb    SPLUNK_BUCKET   1970-01-16  1970-01-16  153 MB  hdfs://localhost:9000/archiver_root/archive_data/mycluster/hiro/mytestdb/db_1333563572_1333523435_46/SPLUNK_BUCKET

**Comment by petterik** [comment]
Commit: f27cea8e3 fixes this.
The problem was that the bucket's name contained times in seconds, and java.util.date takes milliseconds.
