### ISSUE TITLE
If thaw request is issued while thaw is in progress, potential spurious errors

### ISSUE THREAD

**Issue by borischen** [splunk/splunk-shuttl#66]
We already handle the case where subsequent thaw requests are issued against a time range. The second thaw request will simply get any additional files that isn't already being transferred and skip the rest. In the end, you should get everything. But, yet the UI flags the skipped buckets as failed buckets which is wrong.

**Comment by petterik** [comment]
Does not show which buckets are skipped or failed in the UI anymore.
