### ISSUE TITLE
thaw operation in UI should restrict to SPLUNK_BUCKET for now

### ISSUE THREAD

**Issue by borischen** [splunk/splunk-shuttl#70]
Right now, CSV import may place a very high load on Splunk, due to the fact that Splunk doesn't throttle the input.

Until we have something that regulates resource utilization, we should avoid CSV for the purpose of thawing to Splunk.

**Comment by petterik** [comment]
There are many ways of doing this, and I don't think it's necessary before .conf.
If we restrict it in the UI, we should also restrict it in the server.
We could also solve it by configuring which format you want to thaw.

Today, there's no way of choosing format to thaw. It prioritizes SPLUNK_BUCKET ahead of everything.

I think this is a "won't fix", and we can inform the users that it's expensive instead.

What do you say, @borischen?

**Comment by borischen** [comment]
that's fine, won't fix
