### ISSUE TITLE
shuttl doesn't work with cdh3 due to incompatibiity with apache hadoop

### ISSUE THREAD

**Issue by borischen** [splunk/splunk-shuttl#72]
http://grokbase.com/t/cloudera/cdh-dev/127mrqhsg7/please-help-cdh3u4-compatibility-with-apache-hadoop-clients

A client on apache hadoop can't talk to CDH3 :-(

document hackery required to make this work

**Comment by borischen** [comment]
replace hadoop-core.jar, or put in classpath ahead of the lib dir included with shuttl

hadoop-core.jar has a dependency on lib/guava-r09-jarjar.jar (wtf) so include that as well

apparently pentaho found the same to be true http://wiki.pentaho.com/display/BAD/Configure+Pentaho+for+Cloudera+and+Other+Hadoop+Versions

**Comment by petterik** [comment]
What do you want to do here?

**Comment by petterik** [comment]
Did:
1. cd $SPLUNK_HOME/etc/apps/shuttl
2. replace lib/hadoop-core-<version>.jar with cloudera's hadoop-core.jar
3. Cloudera's hadoop-core.jar has a dependency on guava-<version>.jar. So I took the guava-r09-jarjar.jar from where I got the hadoop-core.jar. (It was located in the lib/ directory next to the hadoop-core.jar.)
Works.
Version: cdh3u5
