### ISSUE TITLE
Prevent Duplicate Buckets when using Splunk 5.0 Clustering

### ISSUE THREAD

**Issue by borischen** [splunk/splunk-shuttl#79]
In Splunk 5.0, Splunk will call the cold2Frozen script on replicated buckets, therefore, there will be X number of duplicate buckets. (X being the replication factor configured)

We should dedup on archive. 

However, this will mean on thaw, we won't replicate. Which should be fine, since the data is not lost and a new node with the same name can always be brought up to make the bucket available.

A subsequent improvement would be to re-assign a bucket to another servername.

**Comment by petterik** [comment]
Results:
- New ant targets: cluster-setup and cluster-teardown.
- New test group: cluster-test
- Any indexer can Shuttl buckets as if they are another Shuttl instance. The configuration is provided by communicating with, Cluster Master, Cluster Slave and the Cluster Slave's Shuttl Instance.
- Transactions are considered complete if the file already exists on the archive file system.
- Data transfers of the same buckets can be done in parallel by different servers.

Finally:
- Created QA issue for Splunk 5.0 support: #102
