### ISSUE TITLE
Support warm->cold archiving

### ISSUE THREAD

**Issue by borischen** [splunk/splunk-shuttl#80]
In order to reduce latency, do wam->cold transitions in addition to the cold->frozen.

Include instructions on how to set this up

**Comment by petterik** [comment]
Unlike the coldToFrozen script the warmToCold script also says:
"If you specify a script here, the script becomes responsible for moving the data, and Splunk's native data." - from $SPLUNK_HOME/etc/system/README/indexes.conf.spec

We need to do two operations. These could happen in any order.
a. Shuttl the data to the backend storage.
b. Move the native bucket to the configured cold path.

Shuttl failiures during...
  ..order (a.) then (b.):
    The script would get called while the bucket was still in the warm path. I don't know if it's going to be called multiple times, but that doesn't matter because of how Shuttl locks buckets. The bucket would then stay in warm until we've successfully Shuttl'ed the bucket.
    Pros: It would be the easiest solution to implement, since we would get automatic retries.
    Cons: If the backend storage is down or there's something wrong with Shuttl, the warm path would eventually get full, and Splunk would not be able to index anymore data. Shuttl would not live invisible from the regular Splunk use.
  ..order (b.) then (a.):
    The shuttling script would only be called once and we would have to keep a receipt in the localArchiverDir of which warmToCold buckets have been Shuttl'ed. We could then either retry the buckets that did not succeed to be Shuttl'ed, or we could rely on the coldToFrozen script to eventually Shuttl the bucket, and have eventual consistency.
    Pros: Less pressure on Shuttl and the backend storage to always perform and be available.
    Cons: Harder to implement if we want to rely on the warmToCold script to always Shuttl the data. Eventual consistency should be easy.

I definitely think (b.) then (a.) is a better order.
The first implementation could try to Shuttl data from warmToCold once. And a second one would be keep retrying to Shuttl warmToCold failures.

@borischen: Let me know what you think.

**Comment by petterik** [comment]
So far we have an endpoint that copies the bucket without deleting it afterwards.

**Comment by petterik** [comment]
Here's an interesting notice from the indexes.conf.spec:
- Searches and other activities are paused while the [warmToColdScript] is running.

**Comment by petterik** [comment]
warmToColdScript cannot be configured as the coldToFrozenScript, with the index name after the script. Like so:
`coldToFrozenScript = $SPLUNK_HOME/etc/apps/shuttl/bin/archiveBucket.sh archive-test-index`

Instead the warmToColdScript needs to rely on the path to the bucket, that Splunk gives the script. Iterate over all the indexes in Splunk and find the configured warm-path that is the parent file of the bucket.

**Comment by trumpdeck** [comment]
FYI some customers are asking about this feature
see case 105446

Subject: Upload warm/cold buckets to S3
Description: Hello,
We are interested in uploading our Splunk indexes to S3 to be used by
Elastic MapReduce. We don't want to have to archive the buckets because we
still use Splunk in-house. We have several months of data before it gets
archived/frozen, and we'd like to keep it that way. Is there any way you
know of to do what we want? Shuttl appears to work at the freezing step,
which is too far back to be very useful.
My Google searches haven't turned anything up, so I wanted to ask Splunk
Support to see if you knew of anything.

**Comment by petterik** [comment]
Great!
Warm-to-cold should be released very soon too!
There should probably exist a script for just copying buckets while they are still in warm too, but the user of that script would have to be sure that the bucket is not going to be modified by Splunk any more.

Thanks for the info

**Comment by petterik** [comment]
Waiting for #110. Closing when done.

**Comment by petterik** [comment]
@trumpdeck This is completed now. Tell the customers that have been asking about it :)
