### ISSUE TITLE
Buckets not moved into HDFS

### ISSUE THREAD

**Issue by msnelling** [splunk/splunk-shuttl#82]
I'm struggling with integrating Hadoop 1.0.3 into Shuttl 0.6.3. I believe I've followed what instructions there are and I can see that my frozen buckets are removed from the index.
I've set the following location for the `<localArchiverDir>file:/~/var/lib/shuttl_archiver</localArchiverDir>` in _archiver.xml_ and I can see the buckets in _var/lib/shuttl_archiver/data/safe-buckets/main_ and lock files in _var/lib/shuttl_archiver/data/archive-locks-dir_ but they are never moved into HDFS.
Also I can't see the buckets in the Shuttl UI.

Here's a copy of my _archiver.xml_

``` xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:archiverConf xmlns:ns2="com.splunk.shuttl.server.model">
    <localArchiverDir>file:/~/var/lib/shuttl_archiver</localArchiverDir>
    <archiverRootURI>hdfs://localhost:9000/archiver_root</archiverRootURI>
    <clusterName>cluster_name</clusterName>
    <serverName>ubuntu</serverName>
    <archiveFormats>
        <archiveFormat>SPLUNK_BUCKET</archiveFormat>
    </archiveFormats>
</ns2:archiverConf>
```

**Comment by petterik** [comment]
The archiver.xml looks correct. 
Did you also setup the shuttl/conf/splunk.xml ?
Can you see anything in the $SPLUNK_HOME/var/log/splunk/shuttl.log ? (It should me logged into the shuttl index in your Splunk indexer, if you want to trouble shoot from Splunk instead)
If you see any errors, kill the Shuttl process to restart it.
$ ps -ef | grep Shuttl
$ kill <pid>

**Comment by petterik** [comment]
Also, using the ~ in the <localArchiverDir> could also be a problem, i.e. you're running Splunk as one user and administrating shuttl as another.
You could configure an absolute path to the <localArchiverDir> instead, and move all the files you already have to that new absolute path. And if you do, make sure to restart the ShuttlServer.

**Comment by msnelling** [comment]
Yes shuttl/conf/splunk.xml was configured.

I'm getting the following error in _$SPLUNK_HOME/var/log/shuttl.log_

```
2012-09-24 16:20:44,278 ERROR com.splunk.shuttl.archiver.archive.ArchiveRestHandler: did="Sent archive bucket request" happened="got IOException" expected="request to succeed" exception="org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:9090 refused" bucket_name="db_1346411703_1345061859_6" cause="java.net.ConnectException: Connection refused"
```

When I do a _netstat -a | egrep 9090_ I only see a port 9090 listening on tcp6

```
tcp6       0      0 localhost:9090          [::]:*                  LISTEN
```

There's nothing in _$SPLUNK_HOME/var/log/shuttl-server.log_

**Comment by msnelling** [comment]
In fact it looks like none of the Hadoop processes are listening on IPv4 addresses either. Seems to be isolated to Java.

**Comment by petterik** [comment]
My `netstat -a | egrep 9090` does not catch anything to be honest. But my `lsof -i :9090` does.

Can you verify that the ShuttlServer is indeed up and running by:
$`lsof -i :9090`
`COMMAND PID ..
java    <pid> <user>   79u  IPv6 ...`
$ `ps -ef | grep <pid>
501  7867  7848   0  8:59AM ??         0:07.72 /Library/Java/Home/bin/java -Djetty.home=. -Dsplunk.home=../../../../ -cp .:../lib/*:./* com.splunk.shuttl.server.ShuttlJettyServer`

I see that we run java exclusively from $JAVA_HOME/bin/java in the shuttl/bin/start.sh
So if you're $JAVA_HOME is not set in the same process tree as Splunk, then it won't start neither.

I will at least create an issue for looking for java in $PATH if $JAVA_HOME is not set, even though this might not be your problem.

Let me know if you find something! I'll be on my way to the office now, so I won't answer within 30 minutes.

Otherwise a Splunk search for "index=_internal Shuttl*" might help you.

**Comment by petterik** [comment]
$ `netstat -nat | grep 9090`
`tcp4       0      0  127.0.0.1.9090         *.*                    LISTEN`
I've got tcp4. I'm not sure if or how this is the problem yet. I just thought I'd let you know.

**Comment by msnelling** [comment]
I tried switching to IPv4 only by using the Java option `-Djava.net.preferIPv4Stack=true` but this had no effect. I can verify that `lsof -i :9090` shows the java shuttl process listening.

I'm installing Shuttl into a pre-existing Splunk installation. When Shuttl is enabled Splunk immediately tries to archive the the old buckets, that is when I get the `2012-09-24 16:20:44,278 ERROR com.splunk.shuttl.archiver.archive.ArchiveRestHandler: did="Sent archive bucket request" happened="got IOException" expected="request to succeed" exception="org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:9090 refused" bucket_name="db_1346411703_1345061859_6" cause="java.net.ConnectException: Connection refused"` error in the _shuttl.log_ file.
Is it trying to archive while the Shuttl server is still starting up? The buckets are moved into the _var/lib/shuttl_archiver/data/safe-buckets/main_ location but remain there not moving into HDFS.

**Comment by msnelling** [comment]
Ok, I think I'm right that when you install Shuttl into an existing Splunk system that when Shuttl starts, any buckets that would be frozen are tried but fail becuase the Shuttl server isn't ready in time.
These bucket remain in the `<localArchiverDir>` indefinitely.
I tested this by enabling an index once Shuttl was running and it worked.

**Comment by petterik** [comment]
I believe you're correct. However, the buckets will not remain in the `<localArchiverDir>` indefinitley. They will be re-tried whenever another bucket is being frozen.

Right now we only retry to freeze a bucket when a bucket is being frozen. Created issue #84 for periodically retrying to freeze buckets that failed.

**Comment by chunmingpoxiao** [comment]
@petterik 
 ERROR ShuttlServer: Error during startup
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:119)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:59)
        at org.eclipse.jetty.server.nio.SelectChannelConnector.open(SelectChannelConnector.java:173)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:311)
        at org.eclipse.jetty.server.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:251)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at org.eclipse.jetty.server.Server.doStart(Server.java:274)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
        at com.splunk.shuttl.server.ShuttlJettyServer.main(ShuttlJettyServer.java:59)

?

**Comment by chunmingpoxiao** [comment]
@petterik   exec -a splunk-bucket-freezer $JAVA_HOME/bin/java -cp ./bin/_:./lib/_ com.splunk.shuttl.archiver.archive.BucketFreezer $index $bucket     

$bucket   is what？？？

i don't know who to set it

**Comment by petterik** [comment]
@chunmingpoxiao Your "Error during startup" is because Splunk doesn't kill the Shuttl server. There will probably be a fix for this in a later Splunk upgrade.
A way around this is to just kill Shuttl, and it'll restart automatically.
1. Find the Shuttl process with `ps -ef | grep shuttl`
2. Kill the Shuttl process with `kill <pid>`, where <pid> is the process id of the Shuttl server.

The $bucket variable is the absolute path to the bucket directory.

**Comment by chunmingpoxiao** [comment]
@petterik 
![1](https://f.cloud.github.com/assets/4122556/408288/9091a7e4-ab2b-11e2-91a6-4ad754cd9af8.jpg)
![2](https://f.cloud.github.com/assets/4122556/408289/91de22c6-ab2b-11e2-823d-4a598b3c596c.jpg)
i don't know why ..it can't connect to hadoop
