### ISSUE TITLE
Retry freezing buckets that failed to be frozen

### ISSUE THREAD

**Issue by petterik** [splunk/splunk-shuttl#84]
Right now we only retry to freeze buckets whenever the coldToFrozen script is called.
This could occur too seldom and make data that could be available for thawing, unavailable for an unnecessary long time.

Create some thing that periodically (every X minutes) freezes everything that's available in `<localArchiverDir>`.

Implementation details:
- It should use the same code as the coldToFrozen script for re-freezing the buckets.

**Comment by chunmingpoxiao** [comment]
i don't understand  "Create some thing that periodically (every X minutes) freezes everything that's available in <localArchiverDir>."。。。

thank you

**Comment by petterik** [comment]
There's now a script configured in default/inputs.conf for retrying to archive all buckets in the safe-buckets directory.
